window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "Palms and Terraces",
  ownerRole: "Owner",
  userInitials: "PT",
  logo: "/assets/logo.jpg",
  painHero:
    "Weddings, birthdays, and pool bookings pile up on Messenger — see the calendar fill and confirm event dates without double-booking.",
  brand: {
    primary: "#1a6b54",
    primaryDark: "#0c3d32",
    accent: "#c9a86c",
  },
  demo: {
    booking: {
      labels: {
        dashboardTitle: "Palms · today",
        dashboardSub: "Pool day + event bookings · Rodriguez venue",
        primary: "Bookings",
        people: "Guests",
        calendar: "Venue calendar",
      },
      stats: [
        { label: "Check-ins today", value: "5" },
        { label: "Occupancy", value: "78%" },
        { label: "Pending", value: "4" },
        { label: "This week", value: "21" },
      ],
      occupancy: { weekend: 91, weekday: 55, pending: 4, weekendLabel: "Sat–Sun" },
      timeline: [
        { time: "8:00 AM", title: "Santos Family", detail: "Day swim · Birthday setup", status: "confirmed" },
        { time: "9:30 AM", title: "Torres barkada", detail: "Pool day · 20 pax", status: "confirmed" },
        { time: "11:00 AM", title: "Rodriguez office outing", detail: "Team day · 35 pax", status: "pending" },
        { time: "1:00 PM", title: "Dela Cruz wedding shoot", detail: "Venue tour · Photo", status: "confirmed" },
        { time: "3:00 PM", title: "Garcia reunion", detail: "Event package · 40 pax", status: "pending" },
      ],
      pendingRequests: [
        {
          id: "PT-1188",
          name: "Rodriguez office outing",
          detail: "Team day · 35 guests",
          date: "Tomorrow · 8:00 AM",
          source: "Messenger",
          amount: "Quote · day",
        },
        {
          id: "PT-1187",
          name: "Garcia reunion",
          detail: "Event package · 40 pax",
          date: "Sat · 9:00 AM",
          source: "Facebook",
          amount: "Quote · event",
        },
        {
          id: "PT-1185",
          name: "Ana Villanueva",
          detail: "Birthday party · 25 pax",
          date: "Sun · 10:00 AM",
          source: "Email",
          amount: "Quote · birthday",
        },
      ],
      primaryList: [
        {
          id: "PT-1190",
          name: "Santos Family",
          detail: "Day swim · Birthday setup",
          date: "Today · 8:00 AM",
          status: "confirmed",
        },
        {
          id: "PT-1189",
          name: "Torres barkada",
          detail: "Pool day · 20 pax",
          date: "Today · 9:30 AM",
          status: "confirmed",
        },
        {
          id: "PT-1188",
          name: "Rodriguez office outing",
          detail: "Team day · 35 guests",
          date: "Tomorrow · 8:00 AM",
          status: "pending",
        },
        {
          id: "PT-1187",
          name: "Garcia reunion",
          detail: "Event package · 40 pax",
          date: "Sat · 9:00 AM",
          status: "pending",
        },
        {
          id: "PT-1186",
          name: "Dela Cruz wedding shoot",
          detail: "Venue tour · Photo",
          date: "Sun · 1:00 PM",
          status: "confirmed",
        },
      ],
      calendarEvents: [1, 4, 7, 10, 12, 15, 18, 21, 24, 27],
      people: [
        { name: "Santos Family", meta: "3 visits · Birthday repeat", tag: "Repeat" },
        { name: "Torres barkada", meta: "2 visits · Weekend regulars", tag: "VIP" },
        { name: "Rodriguez office outing", meta: "Corporate · 35 pax", tag: "Corporate" },
        { name: "Ana Villanueva", meta: "Email inquiry · Birthday", tag: "New" },
      ],
      settings: [
        { label: "Day package", value: "Quote on inquiry" },
        { label: "Event / wedding", value: "Custom quote" },
        { label: "Location", value: "Chico St., Torres Subd., San Jose, Rodriguez" },
        { label: "Email", value: "palms.and.terraces@gmail.com" },
      ],
      pages: {
        packages: {
          title: "Venue packages",
          items: [
            { name: "Day swim · family / barkada", price: "Quote on inquiry" },
            { name: "Birthday party package", price: "Quote on inquiry" },
            { name: "Wedding / event venue", price: "Custom quote" },
            { name: "Forum / gathering", price: "Custom quote" },
          ],
        },
      },
    },
  },
};
