window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "Villa Apolonia Resort Hotel",
  ownerRole: "Owner",
  userInitials: "VA",
  logo: "/assets/logo.jpg",
  painHero:
    "Stop taking room and day-stay bookings only on Messenger — see which dates are taken and confirm guests from one calendar.",
  brand: {
    primary: "#c9a227",
    primaryDark: "#1a2f2b",
    accent: "#eef4f1",
  },
  demo: {
    booking: {
      labels: {
        dashboardTitle: "Villa Apolonia · today",
        dashboardSub: "Day stays + overnight rooms · Maly, San Mateo",
        primary: "Bookings",
        people: "Guests",
        calendar: "Resort calendar",
      },
      stats: [
        { label: "Check-ins today", value: "4" },
        { label: "Occupancy", value: "72%" },
        { label: "Pending", value: "3" },
        { label: "This week", value: "17" },
      ],
      occupancy: { weekend: 88, weekday: 51, pending: 3, weekendLabel: "Sat–Sun" },
      timeline: [
        { time: "8:00 AM", title: "Maly family day", detail: "Day stay · Pool grounds", status: "confirmed" },
        { time: "10:00 AM", title: "Santos overnight", detail: "2 rooms · check-in", status: "confirmed" },
        { time: "11:30 AM", title: "Barkada inquiry", detail: "Day stay · 18 pax", status: "pending" },
        { time: "2:00 PM", title: "Reyes staycation", detail: "Overnight · 1 room", status: "confirmed" },
        { time: "4:00 PM", title: "Day stay wrap", detail: "Checkout · Day guests", status: "confirmed" },
      ],
      pendingRequests: [
        {
          id: "VA-214",
          name: "Cruz weekend stay",
          detail: "2 rooms · Sat–Sun",
          date: "Sat · 2:00 PM",
          source: "Messenger",
          amount: "Quote · overnight",
        },
        {
          id: "VA-213",
          name: "San Mateo barkada",
          detail: "Day stay · 20 pax",
          date: "Sun · 9:00 AM",
          source: "Facebook",
          amount: "Quote · day",
        },
        {
          id: "VA-212",
          name: "Villanueva reunion",
          detail: "Day stay · 25 pax",
          date: "Sat · 8:00 AM",
          source: "SMS",
          amount: "Quote · day",
        },
      ],
      primaryList: [
        {
          id: "VA-216",
          name: "Maly family day",
          detail: "Day stay · Pool grounds",
          date: "Today · 8:00 AM",
          status: "confirmed",
        },
        {
          id: "VA-215",
          name: "Santos overnight",
          detail: "2 rooms · check-in",
          date: "Today · 10:00 AM",
          status: "confirmed",
        },
        {
          id: "VA-214",
          name: "Cruz weekend stay",
          detail: "2 rooms · Sat–Sun",
          date: "Sat · 2:00 PM",
          status: "pending",
        },
        {
          id: "VA-213",
          name: "San Mateo barkada",
          detail: "Day stay · 20 pax",
          date: "Sun · 9:00 AM",
          status: "pending",
        },
        {
          id: "VA-211",
          name: "Reyes staycation",
          detail: "Overnight · 1 room",
          date: "Today · 2:00 PM",
          status: "confirmed",
        },
      ],
      calendarEvents: [2, 5, 8, 11, 14, 16, 19, 22, 25, 28],
      people: [
        { name: "Maly family", meta: "3 day visits · Local", tag: "Repeat" },
        { name: "Santos overnight", meta: "2 rooms · Weekend", tag: "VIP" },
        { name: "Cruz weekend", meta: "Pending · Messenger", tag: "Hot" },
        { name: "San Mateo barkada", meta: "Day stay · FB inquiry", tag: "New" },
      ],
      settings: [
        { label: "Location", value: "Maly-Maarang Road, Brgy. Maly, San Mateo" },
        { label: "SMART", value: "0968 306 6345" },
        { label: "PLDT", value: "(02) 8788 2475" },
        { label: "Email", value: "newvarh@gmail.com" },
      ],
    },
  },
};
