window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "Merlita's Private Resort",
  ownerRole: "Owner",
  userInitials: "MP",
  logo: "/assets/logo.jpg",
  painHero:
    "Day and overnight staycation bookings stack up on Messenger — see the calendar fill and confirm private resort dates without double-booking.",
  brand: {
    primary: "#c9a86c",
    primaryDark: "#0f3d36",
    accent: "#e8f2ee",
  },
  demo: {
    booking: {
      labels: {
        dashboardTitle: "Merlita · today",
        dashboardSub: "Day tour + overnight stays · Rodriguez venue",
        primary: "Bookings",
        people: "Guests",
        calendar: "Resort calendar",
      },
      stats: [
        { label: "Check-ins today", value: "4" },
        { label: "Occupancy", value: "82%" },
        { label: "Pending", value: "3" },
        { label: "This week", value: "18" },
      ],
      occupancy: { weekend: 94, weekday: 58, pending: 3, weekendLabel: "Sat–Sun" },
      timeline: [
        { time: "8:00 AM", title: "Saturinas Family", detail: "Day package · Private resort", status: "confirmed" },
        { time: "9:30 AM", title: "Alex & Eight", detail: "Venue tour · Event inquiry", status: "confirmed" },
        { time: "12:00 PM", title: "Reyes barkada", detail: "Day swim · 18 pax", status: "pending" },
        { time: "8:00 PM", title: "Garcia overnight", detail: "Overnight stay · 10 pax", status: "confirmed" },
        { time: "9:00 PM", title: "Cruz celebration", detail: "Venue night · 25 pax", status: "pending" },
      ],
      pendingRequests: [
        {
          id: "BK-2204",
          name: "Reyes barkada",
          detail: "Day package · 18 guests",
          date: "Tomorrow · 8:00 AM",
          source: "Messenger",
          amount: "Quote · day",
        },
        {
          id: "BK-2203",
          name: "Cruz celebration",
          detail: "Overnight venue · 25 pax",
          date: "Sat · 8:00 PM",
          source: "Facebook",
          amount: "Quote · overnight",
        },
        {
          id: "BK-2201",
          name: "Montalban reunion",
          detail: "Day + event setup · 30 pax",
          date: "Sun · 8:00 AM",
          source: "SMS",
          amount: "Quote · event",
        },
      ],
      primaryList: [
        {
          id: "BK-2206",
          name: "Saturinas Family",
          detail: "Day package · Private resort",
          date: "Today · 8:00 AM",
          status: "confirmed",
        },
        {
          id: "BK-2205",
          name: "Garcia overnight",
          detail: "Overnight stay · 10 pax",
          date: "Today · 8:00 PM",
          status: "confirmed",
        },
        {
          id: "BK-2204",
          name: "Reyes barkada",
          detail: "Day package · 18 guests",
          date: "Tomorrow · 8:00 AM",
          status: "pending",
        },
        {
          id: "BK-2203",
          name: "Cruz celebration",
          detail: "Overnight venue · 25 pax",
          date: "Sat · 8:00 PM",
          status: "pending",
        },
        {
          id: "BK-2202",
          name: "Alex & Eight",
          detail: "Venue tour · Event inquiry",
          date: "Sun · 10:00 AM",
          status: "confirmed",
        },
      ],
      calendarEvents: [2, 5, 8, 11, 13, 16, 19, 22, 25, 28],
      people: [
        { name: "Saturinas Family", meta: "2 visits · Day package", tag: "Repeat" },
        { name: "Garcia overnight", meta: "1 overnight · FB inquiry", tag: "New" },
        { name: "Reyes barkada", meta: "Pending · Messenger", tag: "Hot" },
        { name: "Cruz celebration", meta: "Event night · Quote sent", tag: "Event" },
      ],
      settings: [
        { label: "Daytime hours", value: "8:00 AM – 5:00 PM" },
        { label: "Overnight hours", value: "8:00 PM – 5:00 AM" },
        { label: "Location", value: "220 E. Manuel St., San Jose, Rodriguez" },
        { label: "Mobile", value: "0949 563 1129" },
      ],
    },
  },
};
