window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "Lucky Drive Inn Hotel",
  ownerRole: "Front desk",
  userInitials: "LD",
  logo: "/assets/logo.jpg",
  painHero:
    "Overnight and drive-in room requests pile up on Messenger — see tonight's occupancy and confirm stays without double-booking.",
  brand: {
    primary: "#1B6B3A",
    primaryDark: "#0B2A5B",
    accent: "#E8B923",
  },
  demo: {
    booking: {
      labels: {
        primary: "Bookings",
        people: "Guests",
        calendar: "Room calendar",
        dashboardTitle: "Lucky Drive Inn · tonight",
        dashboardSub: "Drive-in & overnight stays · Rodriguez Rizal",
      },
      occupancy: {
        weekend: 88,
        weekday: 64,
        pending: 4,
        weekendLabel: "Fri–Sun",
      },
      stats: [
        { label: "Check-ins today", value: "9" },
        { label: "Occupancy", value: "76%" },
        { label: "Pending", value: "4" },
        { label: "This week", value: "31" },
      ],
      timeline: [
        { time: "10:00 AM", title: "Reyes couple", detail: "Themed room · Day rest", status: "confirmed" },
        { time: "1:00 PM", title: "Santos overnight", detail: "Double room · 1 night", status: "confirmed" },
        { time: "4:00 PM", title: "Drive-in walk-in", detail: "Standard room · TBD hours", status: "pending" },
        { time: "7:00 PM", title: "Cruz anniversary", detail: "Mural suite · 2 nights", status: "confirmed" },
        { time: "10:00 PM", title: "Late arrival · Lim", detail: "Overnight · Messenger hold", status: "pending" },
      ],
      pendingRequests: [
        {
          id: "LD-2204",
          name: "Drive-in walk-in",
          detail: "Standard room · tonight",
          date: "Today · 4:00 PM",
          source: "Walk-in",
          amount: "₱1,800",
        },
        {
          id: "LD-2201",
          name: "Late arrival · Lim",
          detail: "Overnight · 1 night",
          date: "Today · 10:00 PM",
          source: "Messenger",
          amount: "₱2,200",
        },
        {
          id: "LD-2198",
          name: "Garcia weekend",
          detail: "Themed room · Fri–Sat",
          date: "Fri · 3:00 PM",
          source: "Facebook",
          amount: "₱4,500",
        },
      ],
      primaryList: [
        {
          id: "LD-2208",
          name: "Reyes couple",
          detail: "Themed room · day rest",
          date: "Today · 10:00 AM",
          status: "confirmed",
        },
        {
          id: "LD-2206",
          name: "Santos overnight",
          detail: "Double · 1 night",
          date: "Today · 1:00 PM",
          status: "confirmed",
        },
        {
          id: "LD-2204",
          name: "Drive-in walk-in",
          detail: "Standard · tonight",
          date: "Today · 4:00 PM",
          status: "pending",
        },
        {
          id: "LD-2201",
          name: "Late arrival · Lim",
          detail: "Overnight hold",
          date: "Today · 10:00 PM",
          status: "pending",
        },
        {
          id: "LD-2195",
          name: "Cruz anniversary",
          detail: "Mural suite · 2 nights",
          date: "Today · 7:00 PM",
          status: "confirmed",
        },
      ],
      calendarEvents: [2, 4, 6, 9, 11, 14, 16, 19, 22, 25, 28],
      people: [
        { name: "Cruz anniversary", meta: "2 stays · mural suite fans", tag: "VIP" },
        { name: "Santos overnight", meta: "Repeat · Rodriguez local", tag: "Repeat" },
        { name: "Lim · late arrival", meta: "New · Messenger inquiry", tag: "New" },
        { name: "Garcia weekend", meta: "Couple · Fri–Sat hold", tag: "Pending" },
      ],
      settings: [
        { label: "Standard overnight", value: "from ₱1,800" },
        { label: "Themed / mural room", value: "from ₱2,200" },
        { label: "Front desk", value: "Always open · 24 hours" },
        { label: "Location", value: "Don Mariano Ave., San Jose, Rodriguez" },
      ],
    },
  },
};
