[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://carlmanuel.com https://www.carlmanuel.com https://carlxaeron.github.io"
    X-Content-Type-Options = "nosniff"
