window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "A and C Private Pool Resort",
  ownerRole: "Owner",
  userInitials: "AC",
  logo: "/assets/logo.jpg",
  painHero:
    "Day swim, pavilion, and room rentals stack up on Messenger — see which dates are taken and confirm private-pool bookings from one calendar.",
  brand: {
    primary: "#5ec8d8",
    primaryDark: "#0a3d4a",
    accent: "#e6f5f7",
  },
  demo: {
    booking: {
      labels: {
        dashboardTitle: "A & C · today",
        dashboardSub: "Private pool · pavilion · rooms · Abuab Rd II, San Mateo",
        primary: "Bookings",
        people: "Guests",
        calendar: "Resort calendar",
      },
      stats: [
        { label: "Check-ins today", value: "4" },
        { label: "Occupancy", value: "72%" },
        { label: "Pending", value: "3" },
        { label: "This week", value: "17" },
      ],
      occupancy: { weekend: 94, weekday: 48, pending: 3, weekendLabel: "Sat–Sun" },
      timeline: [
        { time: "8:00 AM", title: "San Mateo barkada", detail: "Day swim · 18 pax", status: "confirmed" },
        { time: "9:30 AM", title: "Reyes birthday", detail: "Pavilion + pool · videoke", status: "confirmed" },
        { time: "11:00 AM", title: "Cruz family room", detail: "A/C room · 8 beds", status: "pending" },
        { time: "1:00 PM", title: "Villanueva night swim", detail: "Night package · 22 pax", status: "confirmed" },
        { time: "4:00 PM", title: "Day guests wrap", detail: "Checkout · Day entrance", status: "confirmed" },
      ],
      pendingRequests: [
        {
          id: "AC-214",
          name: "Cruz family room",
          detail: "A/C room · 8 beds · weekend",
          date: "Sat · 11:00 AM",
          source: "Messenger",
          amount: "Quote · room",
        },
        {
          id: "AC-213",
          name: "Marikina barkada",
          detail: "Day swim · 20 pax",
          date: "Sun · 8:00 AM",
          source: "Facebook",
          amount: "Quote · day",
        },
        {
          id: "AC-212",
          name: "Garcia pavilion",
          detail: "Pavilion + griller · birthday",
          date: "Sat · 10:00 AM",
          source: "Messenger",
          amount: "Quote · pavilion",
        },
      ],
      primaryList: [
        {
          id: "AC-216",
          name: "San Mateo barkada",
          detail: "Day swim · 18 pax",
          date: "Today · 8:00 AM",
          status: "confirmed",
        },
        {
          id: "AC-215",
          name: "Reyes birthday",
          detail: "Pavilion + pool · videoke",
          date: "Today · 9:30 AM",
          status: "confirmed",
        },
        {
          id: "AC-214",
          name: "Cruz family room",
          detail: "A/C room · 8 beds",
          date: "Sat · 11:00 AM",
          status: "pending",
        },
        {
          id: "AC-213",
          name: "Marikina barkada",
          detail: "Day swim · 20 pax",
          date: "Sun · 8:00 AM",
          status: "pending",
        },
        {
          id: "AC-212",
          name: "Garcia pavilion",
          detail: "Pavilion + griller · birthday",
          date: "Sat · 10:00 AM",
          status: "pending",
        },
      ],
      calendarEvents: [2, 5, 8, 11, 14, 16, 19, 22, 25, 28],
      people: [
        { name: "Reyes birthday", meta: "Pavilion repeat · Local", tag: "Repeat" },
        { name: "San Mateo barkada", meta: "Day swim · 18 pax", tag: "VIP" },
        { name: "Cruz family room", meta: "Pending · Messenger", tag: "Hot" },
        { name: "Marikina barkada", meta: "Day swim · FB inquiry", tag: "New" },
      ],
      settings: [
        { label: "Day entrance (adult)", value: "₱280 · min 15 pax" },
        { label: "Night entrance (adult)", value: "₱350 · min 15 pax" },
        { label: "A/C room (8 beds)", value: "₱2,500" },
        { label: "Pavilion", value: "₱2,500 · videoke till 9 PM" },
        { label: "Location", value: "Abuab Road II, San Mateo, Rizal" },
        { label: "Booking channel", value: "Facebook Messenger" },
      ],
    },
  },
};
