window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "Frances Teresa Garden",
  ownerRole: "Owner",
  userInitials: "FT",
  logo: "../assets/logo.jpg",
  painHero:
    "Wedding, debut, and party bookings pile up on Messenger — see the garden calendar fill and confirm event dates without double-booking.",
  brand: {
    primary: "#3d6b54",
    primaryDark: "#1b3a2f",
    accent: "#d4a574",
  },
  demo: {
    booking: {
      labels: {
        dashboardTitle: "Frances Teresa · today",
        dashboardSub: "Garden events · Rodriguez party venue",
        primary: "Bookings",
        people: "Guests",
        calendar: "Venue calendar",
      },
      stats: [
        { label: "Events today", value: "3" },
        { label: "Weekend fill", value: "91%" },
        { label: "Pending", value: "4" },
        { label: "This week", value: "12" },
      ],
      occupancy: { weekend: 91, weekday: 54, pending: 4, weekendLabel: "Sat–Sun" },
      timeline: [
        { time: "9:00 AM", title: "Reyes debut setup", detail: "Garden debut · styling crew", status: "confirmed" },
        { time: "11:00 AM", title: "Santos wedding tour", detail: "Venue walkthrough · bridal cars", status: "confirmed" },
        { time: "1:00 PM", title: "Cruz baptismal", detail: "Garden party · 80 pax", status: "pending" },
        { time: "3:00 PM", title: "Montalban reunion", detail: "Family reunion · seminar hall", status: "confirmed" },
        { time: "5:00 PM", title: "Photo shoot slot", detail: "Outdoor garden · couple shoot", status: "pending" },
      ],
      pendingRequests: [
        {
          id: "FT-118",
          name: "Cruz baptismal",
          detail: "Garden party · 80 guests",
          date: "Tomorrow · 1:00 PM",
          source: "Messenger",
          amount: "Quote · baptismal",
        },
        {
          id: "FT-117",
          name: "Dela Cruz debut",
          detail: "Debut package · vintage bridal car",
          date: "Sat · 4:00 PM",
          source: "Facebook",
          amount: "Quote · debut",
        },
        {
          id: "FT-115",
          name: "Garcia anniversary",
          detail: "Garden dinner · 60 pax",
          date: "Sun · 5:00 PM",
          source: "Email",
          amount: "Quote · anniversary",
        },
      ],
      primaryList: [
        {
          id: "FT-120",
          name: "Reyes debut setup",
          detail: "Garden debut · styling",
          date: "Today · 9:00 AM",
          status: "confirmed",
        },
        {
          id: "FT-119",
          name: "Santos wedding tour",
          detail: "Walkthrough · bridal cars",
          date: "Today · 11:00 AM",
          status: "confirmed",
        },
        {
          id: "FT-118",
          name: "Cruz baptismal",
          detail: "Garden party · 80 guests",
          date: "Tomorrow · 1:00 PM",
          status: "pending",
        },
        {
          id: "FT-117",
          name: "Dela Cruz debut",
          detail: "Debut · vintage car",
          date: "Sat · 4:00 PM",
          status: "pending",
        },
        {
          id: "FT-116",
          name: "Montalban reunion",
          detail: "Family reunion · seminar",
          date: "Sun · 10:00 AM",
          status: "confirmed",
        },
      ],
      calendarEvents: [1, 4, 7, 9, 12, 14, 16, 18, 21, 23, 26, 28],
      people: [
        { name: "Reyes Family", meta: "2 visits · Debut repeat", tag: "Repeat" },
        { name: "Santos wedding", meta: "Tour booked · Bridal cars", tag: "Wedding" },
        { name: "Cruz baptismal", meta: "Pending · Messenger", tag: "Hot" },
        { name: "Dela Cruz debut", meta: "Quote sent · FB", tag: "Debut" },
      ],
      settings: [
        { label: "Venue hours", value: "Open · events by booking" },
        { label: "Address", value: "698 Tanguile St., San Jose, Rodriguez 1860" },
        { label: "Mobile", value: "0947 705 2252" },
        { label: "Email", value: "ftdl.corp.design@gmail.com" },
      ],
    },
  },
};
