window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "Liz Palmana Resort",
  ownerRole: "Owner",
  userInitials: "LP",
  logo: "/assets/logo.jpg",
  painHero:
    "Stop taking family and friends bookings only on Messenger — see which dates are open and confirm guests from one calendar.",
  brand: {
    primary: "#e8a85c",
    primaryDark: "#0a4a42",
    accent: "#e6f5f1",
  },
  demo: {
    booking: {
      labels: {
        dashboardTitle: "Liz Palmana · today",
        dashboardSub: "Family & friends resort · Malanday, San Mateo",
        primary: "Bookings",
        people: "Guests",
        calendar: "Resort calendar",
      },
      stats: [
        { label: "Check-ins today", value: "4" },
        { label: "Occupancy", value: "72%" },
        { label: "Pending", value: "3" },
        { label: "This week", value: "17" },
      ],
      occupancy: { weekend: 88, weekday: 49, pending: 3, weekendLabel: "Sat–Sun" },
      timeline: [
        { time: "8:00 AM", title: "Malanday family day", detail: "Day package · pool", status: "confirmed" },
        { time: "9:30 AM", title: "Santos barkada", detail: "Day visit · 14 pax", status: "confirmed" },
        { time: "11:00 AM", title: "Reyes overnight", detail: "Staycation inquiry · 2 rooms", status: "pending" },
        { time: "2:00 PM", title: "Cruz celebration", detail: "Family gathering · venue", status: "confirmed" },
        { time: "4:00 PM", title: "Day guests wrap", detail: "Checkout · day package", status: "confirmed" },
      ],
      pendingRequests: [
        {
          id: "LP-118",
          name: "Reyes overnight",
          detail: "2 rooms · weekend stay",
          date: "Sat · 2:00 PM",
          source: "Messenger",
          amount: "Quote · overnight",
        },
        {
          id: "LP-117",
          name: "San Mateo barkada",
          detail: "Day swim · 18 pax",
          date: "Sun · 8:00 AM",
          source: "Facebook",
          amount: "Quote · day",
        },
        {
          id: "LP-116",
          name: "Dela Cruz reunion",
          detail: "Family gathering · venue",
          date: "Sat · 10:00 AM",
          source: "Email",
          amount: "Quote · event",
        },
      ],
      primaryList: [
        {
          id: "LP-120",
          name: "Malanday family day",
          detail: "Day package · pool",
          date: "Today · 8:00 AM",
          status: "confirmed",
        },
        {
          id: "LP-119",
          name: "Cruz celebration",
          detail: "Family gathering · venue",
          date: "Today · 2:00 PM",
          status: "confirmed",
        },
        {
          id: "LP-118",
          name: "Reyes overnight",
          detail: "2 rooms · weekend stay",
          date: "Sat · 2:00 PM",
          status: "pending",
        },
        {
          id: "LP-117",
          name: "San Mateo barkada",
          detail: "Day swim · 18 pax",
          date: "Sun · 8:00 AM",
          status: "pending",
        },
        {
          id: "LP-115",
          name: "Santos barkada",
          detail: "Day visit · 14 pax",
          date: "Today · 9:30 AM",
          status: "confirmed",
        },
      ],
      calendarEvents: [2, 5, 8, 11, 14, 17, 20, 23, 26, 29],
      people: [
        { name: "Malanday family", meta: "2 day visits · Local", tag: "Repeat" },
        { name: "Cruz celebration", meta: "Family gathering", tag: "VIP" },
        { name: "Reyes overnight", meta: "Pending · Messenger", tag: "Hot" },
        { name: "San Mateo barkada", meta: "Day swim · FB inquiry", tag: "New" },
      ],
      settings: [
        { label: "Location", value: "Baltazar Compound, Patiis Rd, Malanday, San Mateo" },
        { label: "Email", value: "lizpalmanaresort@yahoo.com" },
        { label: "Facebook", value: "facebook.com/LizPalmana" },
        { label: "Hours", value: "Always open · confirm by booking" },
      ],
    },
  },
};
