[build]
  publish = "."
  command = ""

[[edge_functions]]
  path = "/*"
  function = "embed-only"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://carlmanuel.com https://www.carlmanuel.com https://carlxaeron.github.io http://localhost:3000"
    X-Content-Type-Options = "nosniff"
