window.ADMIN_CONFIG = window.ADMIN_CONFIG || {
  vertical: "booking",
  businessName: "Grand Hyatt Manila",
  ownerRole: "Front Office Manager",
  userInitials: "GH",
  logo: "/assets/logo.png",
  painHero:
    "Room blocks and banquet inquiries land on Messenger and email — see occupancy and VIP arrivals in one place.",
  brand: {
    primary: "#C5A572",
    primaryDark: "#0B0F14",
    accent: "#D4B896",
  },
  demo: {
    booking: {
      labels: {
        primary: "Bookings",
        people: "Guests",
        calendar: "House calendar",
        dashboardTitle: "Grand Hyatt · arrivals",
        dashboardSub: "Rooms, suites, and banquet holds · BGC",
      },
      occupancy: {
        weekend: 94,
        weekday: 81,
        pending: 5,
        weekendLabel: "Fri–Sun",
      },
      stats: [
        { label: "Check-ins today", value: "42" },
        { label: "Occupancy", value: "91%" },
        { label: "Pending holds", value: "5" },
        { label: "Banquets this week", value: "7" },
      ],
      timeline: [
        { time: "6:30 AM", title: "Lim · Grand King", detail: "Early arrival · Club Lounge access", status: "confirmed" },
        { time: "10:00 AM", title: "Tan wedding block", detail: "12 Grand Twins · Floor 28–29", status: "confirmed" },
        { time: "1:00 PM", title: "Ayala board retreat", detail: "Grand Suite + meeting room A", status: "pending" },
        { time: "3:30 PM", title: "Park · Grand Suite", detail: "VIP · Illume Spa package", status: "confirmed" },
        { time: "5:00 PM", title: "Santos family", detail: "2 Grand Kings · connecting", status: "pending" },
      ],
      pendingRequests: [
        {
          id: "GH-8841",
          name: "Ayala board retreat",
          detail: "Grand Suite + meeting room · 18 pax",
          date: "Tomorrow · 1:00 PM",
          source: "Email",
          amount: "₱186,000",
        },
        {
          id: "GH-8838",
          name: "Santos family",
          detail: "2 Grand Kings · 4 nights",
          date: "Fri · 3:00 PM",
          source: "Messenger",
          amount: "₱92,400",
        },
        {
          id: "GH-8835",
          name: "MICE — Pharma summit",
          detail: "Ballroom half-day · 120 pax",
          date: "Sat · 8:00 AM",
          source: "Website",
          amount: "₱310,000",
        },
      ],
      primaryList: [
        {
          id: "GH-8844",
          name: "Lim · Grand King",
          detail: "Club Lounge · 2 nights",
          date: "Today · 6:30 AM",
          status: "confirmed",
        },
        {
          id: "GH-8843",
          name: "Tan wedding block",
          detail: "12 Grand Twins",
          date: "Today · 10:00 AM",
          status: "confirmed",
        },
        {
          id: "GH-8841",
          name: "Ayala board retreat",
          detail: "Grand Suite + meeting room",
          date: "Tomorrow · 1:00 PM",
          status: "pending",
        },
        {
          id: "GH-8838",
          name: "Santos family",
          detail: "2 Grand Kings · connecting",
          date: "Fri · 3:00 PM",
          status: "pending",
        },
        {
          id: "GH-8832",
          name: "Park · Grand Suite",
          detail: "Illume Spa package",
          date: "Today · 3:30 PM",
          status: "confirmed",
        },
      ],
      calendarEvents: [2, 4, 6, 9, 11, 13, 16, 19, 22, 25, 27],
      people: [
        { name: "Park Hae-jin", meta: "8 stays · Club member", tag: "VIP" },
        { name: "Tan wedding party", meta: "Room block · Jul 2026", tag: "Event" },
        { name: "Lim Corporate", meta: "Preferred account", tag: "Corporate" },
        { name: "Santos family", meta: "New inquiry via Messenger", tag: "New" },
      ],
      settings: [
        { label: "Grand King (BAR)", value: "from ₱18,500 / night" },
        { label: "Grand Suite (BAR)", value: "from ₱42,000 / night" },
        { label: "Front desk", value: "24 hours · Always open" },
        { label: "Keys inventory", value: "461 rooms & suites" },
      ],
    },
  },
};
